[build]
builder = "dockerfile"

[deploy]
startCommand = "./pocketbase serve --http=0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

# Настройки масштабирования
[scale]
min = 1
max = 1
memory = 512
cpu = 0.5