[build]
builder = "NIXPACKS"

[deploy]
startCommand = "wget -O /tmp/pocketbase https://github.com/pocketbase/pocketbase/releases/download/v0.22.14/pocketbase_0.22.14_linux_amd64 && chmod +x /tmp/pocketbase && /tmp/pocketbase serve --http=0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 60